# Generated by Django 4.2.6 on 2023-10-30 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=26, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размер пицц',
            },
        ),
        migrations.CreateModel(
            name='PizzaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1')], default=0, unique=True, verbose_name='ID типа')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Тип пиццы',
                'verbose_name_plural': 'Типы пицц',
            },
        ),
        migrations.CreateModel(
            name='PizzaModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('title', models.CharField(max_length=124, verbose_name='Название')),
                ('image', models.URLField(max_length=512, verbose_name='Ссылка на фотографию')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('category', models.IntegerField(choices=[(1, 'Мясная'), (2, 'Вегетарианская'), (3, 'Гриль'), (4, 'Острая'), (5, 'Грибная')], verbose_name='Категория')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Рейтинг')),
                ('sizes', models.ManyToManyField(to='api.pizzasize', verbose_name='Размеры')),
                ('types', models.ManyToManyField(to='api.pizzatype', verbose_name='Типы')),
            ],
            options={
                'verbose_name': 'Пицца',
                'verbose_name_plural': 'Пиццы',
            },
        ),
    ]
