version: '3.7'

services:
  backend:
    volumes:
      - static:/static
    env_file:
      - ./backend/.env.prod
    build:
      context: ./backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
    volumes:
      - frontend:/app/build
    env_file:
      - ./.env.prod
  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  static:
  frontend:
