version: '3.7'

services:
  backend:
    env_file:
      - ./backend/.env.prod
    build:
      context: ./backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/build
    env_file:
      - ./frontend/.env.prod
  nginx:
    build:
      context: ./nginx
    volumes:
      - frontend:/app
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  frontend: